//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ax.DEV.Utility.Resources {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Default {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Default() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ax.DEV.Utility.Resources.Default", typeof(Default).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   전체 행 취소과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ALL_ROW_CANCEL {
            get {
                return ResourceManager.GetString("ALL_ROW_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   전체 행 삭제과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ALL_ROW_DELETE {
            get {
                return ResourceManager.GetString("ALL_ROW_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   닫기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CLS {
            get {
                return ResourceManager.GetString("CLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   엑셀 내보내기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string EXCEL_EXPORT {
            get {
                return ResourceManager.GetString("EXCEL_EXPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   엑셀 바로보기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string EXCEL_OPEN {
            get {
                return ResourceManager.GetString("EXCEL_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   총계과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GRAND_TOTAL {
            get {
                return ResourceManager.GetString("GRAND_TOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   중계과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string INTERMEDIATE_TOTAL {
            get {
                return ResourceManager.GetString("INTERMEDIATE_TOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   스프레드 정보를 모두 엑셀로 내보내었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MSG01 {
            get {
                return ResourceManager.GetString("MSG01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   초기화과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NEW {
            get {
                return ResourceManager.GetString("NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   행 추가과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ROW_ADD {
            get {
                return ResourceManager.GetString("ROW_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   행 취소과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ROW_CANCEL {
            get {
                return ResourceManager.GetString("ROW_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   행 삭제과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ROW_DELETE {
            get {
                return ResourceManager.GetString("ROW_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   소계과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SUBTOTAL {
            get {
                return ResourceManager.GetString("SUBTOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   계과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SUM {
            get {
                return ResourceManager.GetString("SUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   합계과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TOTAL {
            get {
                return ResourceManager.GetString("TOTAL", resourceCulture);
            }
        }
    }
}
