//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Ax.SIS.SD.UI.KIAService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://Kmieai/DMDI/data")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getDataOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            this.Url = global::Ax.SIS.SD.UI.Properties.Settings.Default.Ax_SIS_SD_UI_KIAService_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getDataCompletedEventHandler getDataCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Kmieai/DMDI/data/getData", RequestNamespace="http://Kmieai/DMDI/data", ResponseNamespace="http://Kmieai/DMDI/data", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public O_DATA getData(string HEXADECIMAL, INUPUT_DATA data01) {
            object[] results = this.Invoke("getData", new object[] {
                        HEXADECIMAL,
                        data01});
            return ((O_DATA)(results[0]));
        }
        
        /// <remarks/>
        public void getDataAsync(string HEXADECIMAL, INUPUT_DATA data01) {
            this.getDataAsync(HEXADECIMAL, data01, null);
        }
        
        /// <remarks/>
        public void getDataAsync(string HEXADECIMAL, INUPUT_DATA data01, object userState) {
            if ((this.getDataOperationCompleted == null)) {
                this.getDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetDataOperationCompleted);
            }
            this.InvokeAsync("getData", new object[] {
                        HEXADECIMAL,
                        data01}, this.getDataOperationCompleted, userState);
        }
        
        private void OngetDataOperationCompleted(object arg) {
            if ((this.getDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getDataCompleted(this, new getDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Kmieai/DMDI/data")]
    public partial class INUPUT_DATA {
        
        private TAB_DATA_HEADER[] gET_DATAField;
        
        /// <remarks/>
        public TAB_DATA_HEADER[] GET_DATA {
            get {
                return this.gET_DATAField;
            }
            set {
                this.gET_DATAField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Kmieai/DMDI/data")]
    public partial class TAB_DATA_HEADER {
        
        private string iVNUMField;
        
        private string iVDATField;
        
        private string lIFNRField;
        
        private string mATNRField;
        
        private string zSHOPField;
        
        private string eBELNField;
        
        private string iVQTYField;
        
        private string zAIVAMTField;
        
        private string zANETPRField;
        
        private string zANETWRField;
        
        private string zCGSTField;
        
        private string zSGSTField;
        
        private string zIGSTField;
        
        private string zUGSTField;
        
        private string zATCSField;
        
        private string zHSNSACField;
        
        private string zGSTINField;
        
        private string vEHNOField;
        
        private string iRNField;
        
        private string eWAYBILLField;
        
        private string zNUM1Field;
        
        private string zNUM2Field;
        
        private string zNUM3Field;
        
        private string zNUM4Field;
        
        private string zNUM5Field;
        
        private string zCHAR2Field;
        
        private string zCHAR3Field;
        
        private string zCHAR4Field;
        
        private string zCHAR5Field;
        
        /// <remarks/>
        public string IVNUM {
            get {
                return this.iVNUMField;
            }
            set {
                this.iVNUMField = value;
            }
        }
        
        /// <remarks/>
        public string IVDAT {
            get {
                return this.iVDATField;
            }
            set {
                this.iVDATField = value;
            }
        }
        
        /// <remarks/>
        public string LIFNR {
            get {
                return this.lIFNRField;
            }
            set {
                this.lIFNRField = value;
            }
        }
        
        /// <remarks/>
        public string MATNR {
            get {
                return this.mATNRField;
            }
            set {
                this.mATNRField = value;
            }
        }
        
        /// <remarks/>
        public string ZSHOP {
            get {
                return this.zSHOPField;
            }
            set {
                this.zSHOPField = value;
            }
        }
        
        /// <remarks/>
        public string EBELN {
            get {
                return this.eBELNField;
            }
            set {
                this.eBELNField = value;
            }
        }
        
        /// <remarks/>
        public string IVQTY {
            get {
                return this.iVQTYField;
            }
            set {
                this.iVQTYField = value;
            }
        }
        
        /// <remarks/>
        public string ZAIVAMT {
            get {
                return this.zAIVAMTField;
            }
            set {
                this.zAIVAMTField = value;
            }
        }
        
        /// <remarks/>
        public string ZANETPR {
            get {
                return this.zANETPRField;
            }
            set {
                this.zANETPRField = value;
            }
        }
        
        /// <remarks/>
        public string ZANETWR {
            get {
                return this.zANETWRField;
            }
            set {
                this.zANETWRField = value;
            }
        }
        
        /// <remarks/>
        public string ZCGST {
            get {
                return this.zCGSTField;
            }
            set {
                this.zCGSTField = value;
            }
        }
        
        /// <remarks/>
        public string ZSGST {
            get {
                return this.zSGSTField;
            }
            set {
                this.zSGSTField = value;
            }
        }
        
        /// <remarks/>
        public string ZIGST {
            get {
                return this.zIGSTField;
            }
            set {
                this.zIGSTField = value;
            }
        }
        
        /// <remarks/>
        public string ZUGST {
            get {
                return this.zUGSTField;
            }
            set {
                this.zUGSTField = value;
            }
        }
        
        /// <remarks/>
        public string ZATCS {
            get {
                return this.zATCSField;
            }
            set {
                this.zATCSField = value;
            }
        }
        
        /// <remarks/>
        public string ZHSNSAC {
            get {
                return this.zHSNSACField;
            }
            set {
                this.zHSNSACField = value;
            }
        }
        
        /// <remarks/>
        public string ZGSTIN {
            get {
                return this.zGSTINField;
            }
            set {
                this.zGSTINField = value;
            }
        }
        
        /// <remarks/>
        public string VEHNO {
            get {
                return this.vEHNOField;
            }
            set {
                this.vEHNOField = value;
            }
        }
        
        /// <remarks/>
        public string IRN {
            get {
                return this.iRNField;
            }
            set {
                this.iRNField = value;
            }
        }
        
        /// <remarks/>
        public string EWAYBILL {
            get {
                return this.eWAYBILLField;
            }
            set {
                this.eWAYBILLField = value;
            }
        }
        
        /// <remarks/>
        public string ZNUM1 {
            get {
                return this.zNUM1Field;
            }
            set {
                this.zNUM1Field = value;
            }
        }
        
        /// <remarks/>
        public string ZNUM2 {
            get {
                return this.zNUM2Field;
            }
            set {
                this.zNUM2Field = value;
            }
        }
        
        /// <remarks/>
        public string ZNUM3 {
            get {
                return this.zNUM3Field;
            }
            set {
                this.zNUM3Field = value;
            }
        }
        
        /// <remarks/>
        public string ZNUM4 {
            get {
                return this.zNUM4Field;
            }
            set {
                this.zNUM4Field = value;
            }
        }
        
        /// <remarks/>
        public string ZNUM5 {
            get {
                return this.zNUM5Field;
            }
            set {
                this.zNUM5Field = value;
            }
        }
        
        /// <remarks/>
        public string ZCHAR2 {
            get {
                return this.zCHAR2Field;
            }
            set {
                this.zCHAR2Field = value;
            }
        }
        
        /// <remarks/>
        public string ZCHAR3 {
            get {
                return this.zCHAR3Field;
            }
            set {
                this.zCHAR3Field = value;
            }
        }
        
        /// <remarks/>
        public string ZCHAR4 {
            get {
                return this.zCHAR4Field;
            }
            set {
                this.zCHAR4Field = value;
            }
        }
        
        /// <remarks/>
        public string ZCHAR5 {
            get {
                return this.zCHAR5Field;
            }
            set {
                this.zCHAR5Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Kmieai/DMDI/data")]
    public partial class TAB_DATA {
        
        private string iVNUMField;
        
        private string iVDATField;
        
        private string lIFNRField;
        
        private string iFFAILMSGField;
        
        private string iFRESULTField;
        
        /// <remarks/>
        public string IVNUM {
            get {
                return this.iVNUMField;
            }
            set {
                this.iVNUMField = value;
            }
        }
        
        /// <remarks/>
        public string IVDAT {
            get {
                return this.iVDATField;
            }
            set {
                this.iVDATField = value;
            }
        }
        
        /// <remarks/>
        public string LIFNR {
            get {
                return this.lIFNRField;
            }
            set {
                this.lIFNRField = value;
            }
        }
        
        /// <remarks/>
        public string IFFAILMSG {
            get {
                return this.iFFAILMSGField;
            }
            set {
                this.iFFAILMSGField = value;
            }
        }
        
        /// <remarks/>
        public string IFRESULT {
            get {
                return this.iFRESULTField;
            }
            set {
                this.iFRESULTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Kmieai/DMDI/data")]
    public partial class O_DATA {
        
        private TAB_DATA[] gET_DATA_01Field;
        
        /// <remarks/>
        public TAB_DATA[] GET_DATA_01 {
            get {
                return this.gET_DATA_01Field;
            }
            set {
                this.gET_DATA_01Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void getDataCompletedEventHandler(object sender, getDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public O_DATA Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((O_DATA)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591